-- Table: public.itemCategories

-- DROP TABLE IF EXISTS public."itemCategories";

CREATE TABLE IF NOT EXISTS public."itemCategories"
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    "categoryName" text COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT "itemCategories_pkey" PRIMARY KEY (id),
    CONSTRAINT "itemCategories_categoryName_key" UNIQUE ("categoryName")
)

-- Table: public.items

-- DROP TABLE IF EXISTS public.items;

CREATE TABLE IF NOT EXISTS public.items
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    "itemName" text COLLATE pg_catalog."default" NOT NULL,
    "forSale" boolean NOT NULL DEFAULT false,
    "forStock" boolean NOT NULL DEFAULT false,
    "categoryId" bigint NOT NULL,
    "brandId" bigint,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    created_by uuid DEFAULT auth.uid(),
    updated_at timestamp with time zone,
    updated_by uuid DEFAULT gen_random_uuid(),
    CONSTRAINT items_pkey PRIMARY KEY (id),
    CONSTRAINT "items_itemName_key" UNIQUE ("itemName"),
    CONSTRAINT "items_categoryId_fkey" FOREIGN KEY ("categoryId")
        REFERENCES public."itemCategories" (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

-- Table: public.itemUnits

-- DROP TABLE IF EXISTS public."itemUnits";

CREATE TABLE IF NOT EXISTS public."itemUnits"
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    "itemId" bigint NOT NULL,
    "unitName" text COLLATE pg_catalog."default" DEFAULT 'pcs'::text,
    factor smallint DEFAULT '1'::smallint,
    "costPrice" double precision DEFAULT '0'::double precision,
    "salePrice" double precision DEFAULT '0'::double precision,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    created_by uuid NOT NULL DEFAULT auth.uid(),
    updated_at time with time zone,
    updated_by timestamp with time zone,
    CONSTRAINT "itemUnits_pkey" PRIMARY KEY (id),
    CONSTRAINT "itemUnits_itemId_fkey" FOREIGN KEY ("itemId")
        REFERENCES public.items (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

-- Table: public.sales

-- DROP TABLE IF EXISTS public.sales;

CREATE TABLE IF NOT EXISTS public.sales
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    customer text COLLATE pg_catalog."default",
    "billedAmount" double precision DEFAULT '0'::double precision,
    discount double precision DEFAULT '0'::double precision,
    "payableAmount" double precision DEFAULT '0'::double precision,
    "paidUpi" double precision DEFAULT '0'::double precision,
    "paidCash" double precision DEFAULT '0'::double precision,
    "totalPaid" double precision DEFAULT '0'::double precision,
    "invoiceDate" date NOT NULL,
    status text COLLATE pg_catalog."default" NOT NULL DEFAULT 'DRAFT'::text,
    "paymentDate" date,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    created_by uuid DEFAULT auth.uid(),
    updated_at timestamp with time zone,
    updated_by uuid,
    CONSTRAINT sales_pkey PRIMARY KEY (id)
)

-- Table: public.saleDetails

-- DROP TABLE IF EXISTS public."saleDetails";

CREATE TABLE IF NOT EXISTS public."saleDetails"
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    "salesId" bigint NOT NULL,
    "itemId" bigint NOT NULL,
    "itemName" text COLLATE pg_catalog."default",
    unit text COLLATE pg_catalog."default",
    price double precision DEFAULT '0'::double precision,
    quantity bigint DEFAULT '0'::bigint,
    amount double precision DEFAULT '0'::double precision,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    created_by uuid DEFAULT auth.uid(),
    updated_at timestamp with time zone,
    updated_by uuid,
    CONSTRAINT "saleDetails_pkey" PRIMARY KEY (id)
)

-- Table: public.purchases

-- DROP TABLE IF EXISTS public."purchases";
CREATE TABLE IF NOT EXISTS public.purchases
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 ),
    "vendorName" text COLLATE pg_catalog."default" NOT NULL DEFAULT 'RETAIL'::text,
	"vendorAddress" text COLLATE pg_catalog."default",
	"vendorPhone" bigint,
    "billedAmount" double precision DEFAULT '0'::double precision,
    discount double precision DEFAULT '0'::double precision,
    "payableAmount" double precision DEFAULT '0'::double precision,
    "paidUpi" double precision DEFAULT '0'::double precision,
    "paidCash" double precision DEFAULT '0'::double precision,
    "totalPaid" double precision DEFAULT '0'::double precision,
    "invoiceDate" date NOT NULL,
    status text COLLATE pg_catalog."default" NOT NULL DEFAULT 'DRAFT'::text,
    "paymentDate" date,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    created_by uuid DEFAULT auth.uid(),
    updated_at timestamp with time zone,
    updated_by uuid,
    CONSTRAINT purchases_pkey PRIMARY KEY (id)
)

-- Table: public.purchaseDetails

-- DROP TABLE IF EXISTS public."purchaseDetails";
CREATE TABLE IF NOT EXISTS public."purchaseDetails"
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 ),
    "purchaseId" bigint NOT NULL,
    "itemId" bigint NOT NULL,
    "itemName" text COLLATE pg_catalog."default",
    unit text COLLATE pg_catalog."default",
    price double precision DEFAULT '0'::double precision,
    quantity bigint DEFAULT '0'::bigint,
    amount double precision DEFAULT '0'::double precision,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    created_by uuid DEFAULT auth.uid(),
    updated_at timestamp with time zone,
    updated_by uuid,
    CONSTRAINT "purchaseDetails_pkey" PRIMARY KEY (id)
)